name: english_club
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  build_runner: ^2.5.4
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.4
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  image_picker: ^1.1.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5
  lottie: ^3.3.1
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.5.0
  retrofit_generator: 9.2.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/auth.jpg
    - assets/images/roadImage.png
    - assets/images/test.png
    - assets/images/readImage1.png
    - assets/images/openBookTitle.png
    - assets/images/readImage2.png
    - assets/images/borrowBook.png
    - assets/images/background.png
    - assets/images/studentScore.png
    - assets/images/homeBack.png
    - assets/images/studentLevel.png
    - assets/images/finishedStudentStories.png
    - assets/images/golden.png
    - assets/images/bronze.png
    - assets/images/circle.png
    - assets/images/openbook.png
    - assets/images/circleBackground.png
    - assets/images/backRoad.png
    - assets/images/road.png
    - assets/images/bookCover.jpg
    - assets/images/silver.png
    - assets/lotties/scroll.json
    - assets/lotties/read.json
    - assets/lotties/read2.json
    - assets/lotties/catReading.json
    - assets/lotties/noData.json
    - assets/lotties/catReading2.json
    - assets/lotties/roadCick.json
    - assets/lotties/roadCick2.json
    - assets/lotties/empty.json
    - assets/lotties/step.json
    - assets/images/auth1.jpg
    - assets/lotties/celebrate.json
    - assets/images/auth2.jpg
    - assets/images/englishClubText.png
    - assets/images/Reading-glasses-rafiki.png
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
