import 'package:json_annotation/json_annotation.dart';

part 'create_admin_request_body.g.dart';

@JsonSerializable()
class CreateAdminRequestBody {
  final String name;

  CreateAdminRequestBody({required this.name});

  /// Converts a [CreateAdminRequestBody] instance to a JSON map.
  /// This method is automatically generated by `json_serializable`.
  Map<String, dynamic> toJson() => _$CreateAdminRequestBodyToJson(this);

  // Note: A fromJson factory is typically not needed for request bodies
  // as they are usually serialized to JSON, not deserialized from it.
}
